baseurl = "https://nicodoggie.github.io/language-orferithri"
languageCode = "en-us"
title = "Orferitheri Language"
theme = "hugo-steam-theme"
disqusShortname = ""
# Enable Google Analytics be inserting your tracking code
googleAnalytics = ""
# Number of posts per page
paginate = 10

[params]
	title = "Orferithri Language"
	subtitle = "Language of the Orferi People"
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themecolor = "green"

	# Link custom assets relative to /static
	favicon   = "favicon.ico"
	customCSS = []
	customJS  = []

	name = "Nico Suarez"
	description = "Notes, grammar and culture of the Orferi People"
	
	# Link your social networks (optional)
	location = ""
	twitter = "nicodoggie"
	linkedin = ""
	googleplus = ""
	facebook = "nicodoggie"
	instagram = ""
	github = "nicodoggie"
	gitlab = ""

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"